### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by BarbzYHOOL** [jonlabelle/ci-markdown#12]
Just wanted to say this is awesome, and very easy to install and use.

Thank you!

Btw I didn't know all the possibilities of markdown-extra until i read carefully the original site. Might be interesting to put a more elaborate example.

```
# Heading

## Subheading with ID {#my_header}

### Subsubheading with class {.my_class}

<div style="color: purple" markdown=1>
    <http://google.com>
</div>

_italic_ **bold**
```

More on: https://michelf.ca/projects/php-markdown/dingus/

**Comment by jonlabelle** [comment]
Thanks @BarbzYHOOL!
