### ISSUE TITLE
Abbreviations improvement

### ISSUE THREAD

**Issue by BarbzYHOOL** [jonlabelle/ci-markdown#13]
Predefined abbreviations are very useful but they don't work in specific cases:

- if the abbreviation is singular, then the plural form won't be detected as an abbr. There could be a way to define this per abbreviation eventually? atm forced to duplicate each abbr
- If the abbreviation has one uppercase character, then it won't be detected, but sometimes acronyms have weird casing, or putting an abbr on a simple word which is the first word in a sentence means it won't be detected

**Comment by jonlabelle** [comment]
Hi @BarbzYHOOL. This repository ([ci-markdown](https://github.com/jonlabelle/ci-markdown/)) is merely a port of the [PHP Markdown](https://github.com/michelf/php-markdown) library; thus such suggestions should be made to [PHP Markdown](https://github.com/michelf/php-markdown/issues), and following their respective guidelines for improvements.
