### ISSUE TITLE
How to replace specific <span> like actually with <abbr>?

### ISSUE THREAD

**Issue by BarbzYHOOL** [jonlabelle/ci-markdown#14]
I'd like to explain some words, but they are not abbreviations, so it's wrong to explain these words with <abbr title="">

I just would like to reproduce the system of abbrs but with some changes and only to certain <span>, any idea how to proceed?

I read the code a bit but it looked very confusing, with meaningless names etc

**Comment by jonlabelle** [comment]
Hi @BarbzYHOOL. This repository ([ci-markdown](https://github.com/jonlabelle/ci-markdown/)) is merely a port of the [PHP Markdown](https://github.com/michelf/php-markdown) library; thus such suggestions should be made to [PHP Markdown](https://github.com/michelf/php-markdown/issues), and following their respective guidelines for improvements.
