### ISSUE TITLE
Configuration per "page" ?

### ISSUE THREAD

**Issue by BarbzYHOOL** [jonlabelle/ci-markdown#16]
https://michelf.ca/projects/php-markdown/configuration/ how can I set "no_markup" only for one page? actually the conf is global, how can i overwrite the conf specifically on one page?

example: i want to allow html tags in my admin panel, but not when users post comments

**Comment by jonlabelle** [comment]
Great suggestion! Add now supported!

To programmatically configure the Markdown instance, overriding any matched
settings defined in the [config file](config/markdown.php):

```php
$config = array(
    'tab_width' => 2,
    'no_markup' => true,
    'empty_element_suffix' => '/>'
);

$this->load->library('markdown', $config);
```
