### ISSUE TITLE
Codeigniter Error

### ISSUE THREAD

**Issue by radiopromohub** [jonlabelle/ci-markdown#17]
I keep running into this error

> A PHP Error was encountered
> 
> Severity: Notice
> 
> Message: Undefined property: CI_Loader::$markdown
> 
> Filename: views/view_article.php
> 
> Line Number: 68

I am saving the Markdown data in a database and pulling that from the database and displaying in my code like this:

> $string = $a->body;
> $this->load->library('markdown');
> echo $this->markdown->parse($string);

As soon as I remove "echo $this->markdown->parse($string);", I get no errors. 

Any suggestions would help.

**Comment by jonlabelle** [comment]
Try adding `markdown` to your `config/autoload.config` file:

```php
$autoload['libraries'] = array('somelib', 'someotherlib', 'markdown');
```
