### ISSUE TITLE
Issue with markdown transform of nested lists

### ISSUE THREAD

**Issue by Bliksempie** [jonlabelle/ci-markdown#18]
Hi,

From some articles I have read, it appears that the markdown standard has issues with code blocks and nested lists: the two are getting mixed up, so nested lists are styled the way code blocks would be styled.

The advice of the people on the forum is to use two spaces instead, but that makes it render as a paragraph.

To test it out:

    $this->markdown->transform('  1.1. Hello');
    $this->markdown->transform('    1.1. Hello');

You will see that the first one renders in a paragraph tag and the second one as a code block.

I guess it can be disputed as to where the issue lies (with the renderer or with markdown itself) but I figured that, since this issue is almost 10 years old, the markdown syntax won't be fixed (if it is at fault).

Is there something you can do about it?

**Comment by jonlabelle** [comment]
Hi @Bliksempie. Since this library is just a port of [PHPMarkdown](https://michelf.ca/projects/php-markdown/configuration/), I would suggest bringing up your issue w/ [PHPMarkdown](https://github.com/michelf/php-markdown).
