### ISSUE TITLE
Adding custom syntax

### ISSUE THREAD

**Issue by connorgurney** [jonlabelle/ci-markdown#4]
Any way we can extend this to add our own syntax?

**Comment by jonlabelle** [comment]
Well, the short answer, and in its current state, is not really. The *CodeIgniter* rendition is based off the classic versions of [PHP Markdown and PHP Markdown Extra](https://michelf.ca/projects/php-markdown/classic/), so it is configurable, but not necessarily extendable. However, it wouldn't take much to support extensions, and I'm very open to pull requests :).

**Comment by connorgurney** [comment]
I'm just wondering because the UK Government's website uses a customised version, GovSpeak which they have publicly released... https://github.com/alphagov/govspeak.

I wondered if we could adapt this as they have done with their version of Markdown? :smile:
