### ISSUE TITLE
XSS in Markdown

### ISSUE THREAD

**Issue by infinityimagine** [jonlabelle/ci-markdown#6]
It is possible to create a link which when clicked will trigger an XSS.
Reproduction:
Create a link as follows:

> `[Click Me](javascript:alert(9);)`

**Comment by jonlabelle** [comment]
unfortunately no.

**Comment by infinityimagine** [comment]
No? As in you don't intend to fix it? 
Is it okay if i provide the fix for it?

**Comment by jonlabelle** [comment]
you should submit your enhancement request to the [source PHP Markdown repo](https://github.com/michelf/php-markdown). if it gets approved there, it will be merged into this repository. though i doubt it will be considered since it introduces xss/security vunerabilities.

**Comment by infinityimagine** [comment]
I think we have a misunderstanding here.
I am not submitting an enhancement here. I am actually reporting a vulnerability that exists in your version of markdown.

**Comment by jonlabelle** [comment]
_you should submit your enhancement request to the [source PHP Markdown repo](https://github.com/michelf/php-markdown). if it gets approved there, it will be merged into this repository._
