### ISSUE TITLE
How to get class in blockquote?

### ISSUE THREAD

**Issue by natanfelles** [jonlabelle/ci-markdown#8]
Hello!

I have the following code:

```markdown
{: .note}
>
>Allowing unrestricted access to MySQL on a public IP not advised, but you may change the address it listens on by modifying the `bind-address` parameter in `/etc/my.cnf`. If you decide to bind MySQL to your public IP, you should implement firewall rules that only allow connections from specific IP addresses.
```

And the library translate it to:

```html
<p>{: .note}
></p>

<blockquote>
  <p>Allowing unrestricted access to MySQL on a public IP not advised, but you may change the address it listens on by modifying the <code>bind-address</code> parameter in <code>/etc/my.cnf</code>. If you decide to bind MySQL to your public IP, you should implement firewall rules that only allow connections from specific IP addresses.</p>
</blockquote>
```

Any solution to return a `<blockquote class="note">...`?

Thank you! :smiley:

**Comment by jonlabelle** [comment]
From my findings, it doesn't seem to be supported in the [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/) library... therefore, it wouldn't be available in [CI Markdown](https://github.com/jonlabelle/ci-markdown). 

I did however find another PHP library that may do what you're looking for, called [PHP Markdown Extra Extended](https://github.com/egil/php-markdown-extra-extended).
