### ISSUE TITLE
Cross Site Scripting Vulnerabilty

### ISSUE THREAD

**Issue by nsuchy** [jonlabelle/ci-markdown#9]
The parser allows you to create links with a source such as `javascript:alert('xss')`, this could lead to cross site scripting vulnerabilities when a content security policy is not in use. Thoughts?

**Comment by nsuchy** [comment]
A temporarily solution is to use CodeIgniter's XSS Filtering in addition with the markdown parser however I worry that may have issues and building the filtering into the parser would be beneficial.

For example:
```php
<?php
echo $this->markdown->parse($this->security->xss_clean($content));
```

**Comment by jonlabelle** [comment]
Dupe, see #6.
